language: java
env: 
  - CONTAINER=jboss-as-managed
install: "mvn -P ${CONTAINER} -s settings.xml -DskipTests=true -B install"
script: "mvn -P ${CONTAINER} -s settings.xml test"
jdk:
  - oraclejdk7
  - openjdk6

